### PR TITLE
Update version to 1.120.0

### PR DESCRIPTION
**Pull request by computationalcore**
Safely update version to 1.120.0.

### CODE REVIEW

**Comment by computationalcore** [comment]
@kcwinner, I want to work on other bugs like [addLambdaDataSourceAndResolvers](https://github.com/kcwinner/cdk-appsync-transformer/issues/163), but still waiting on this.

**Comment by kcwinner** [comment]
@computationalcore is there anything specific we need from `1.120.0`? I like keeping it lower simply because it provides more availability. 

I'm also working on a cdk v2 version.

**Comment by computationalcore** [comment]
Got it. 
Nothing specifically from 1.120.0, the problem is: Indirectly, the dependency tree of the original lib project is adding 1 high severity vulnerability to any project that adds it.

Screen Shot 2021-09-10 at 10 21 13

Updated version
Screen Shot 2021-09-10 at 10 25 47

**Comment by kcwinner** [comment]
Superseded by https://github.com/kcwinner/cdk-appsync-transformer/pull/276

Bumped package versions and projen versions.

**Pull request closed without merging**
